# Generated by Django 4.0.4 on 2022-12-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='datetime_create',
            field=models.DateTimeField(null=True),
        ),
    ]
