# Generated by Django 4.0.1 on 2022-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
