# Generated by Django 4.0.4 on 2022-12-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_request_cancel'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qrcode', models.ImageField(blank=True, upload_to='static/qrcode')),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Process_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process1', models.CharField(blank=True, max_length=200, null=True)),
                ('process2', models.CharField(blank=True, max_length=200, null=True)),
                ('process3', models.CharField(blank=True, max_length=200, null=True)),
                ('process4', models.CharField(blank=True, max_length=200, null=True)),
                ('process5', models.CharField(blank=True, max_length=200, null=True)),
                ('process6', models.CharField(blank=True, max_length=200, null=True)),
                ('process', models.IntegerField()),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processorders', to='order.order')),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.store')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('allowed', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.order')),
                ('qrcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes', to='payment.qrcode')),
            ],
        ),
    ]
