# Generated by Django 4.0.1 on 2022-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_process_order_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_pay',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_ipn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
