# Generated by Django 4.0.4 on 2022-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
