# Generated by Django 4.0.1 on 2022-12-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('receiver', models.CharField(max_length=50, null=True)),
                ('address_receiver', models.CharField(max_length=200, null=True)),
                ('phone_receiver', models.CharField(max_length=10, null=True)),
                ('status', models.BooleanField()),
                ('total_price', models.FloatField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer')),
                ('transport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_orders', to='order.order')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
