# Generated by Django 4.0.1 on 2022-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_cancel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
