# Generated by Django 4.0.1 on 2022-12-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('order', '0002_transport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer'),
        ),
    ]
